CXX = g++
CXXFLAGS_DEBUG = -Wall -g
CXXFLAGS_OPTIMIZE = -O2

# Source files
MAIN_SOURCES = main.cpp functions.cpp classes.cpp
OPERATORS_SOURCES = operators.cpp functions.cpp classes.cpp

# Common header files
HEADERS = functions.h classes.h

# Output directories
OUTPUT_DIR_DEBUG = debug
OUTPUT_DIR_OPTIMIZE = optimize

# Output filenames
MAIN_OUTPUT_DEBUG = $(OUTPUT_DIR_DEBUG)/main_debug
MAIN_OUTPUT_OPTIMIZE = $(OUTPUT_DIR_OPTIMIZE)/main_optimized
OPERATORS_OUTPUT_DEBUG = $(OUTPUT_DIR_DEBUG)/operators_debug
OPERATORS_OUTPUT_OPTIMIZE = $(OUTPUT_DIR_OPTIMIZE)/operators_optimized

.PHONY: all debug optimize clean

all: debug optimize

debug: $(MAIN_OUTPUT_DEBUG) $(OPERATORS_OUTPUT_DEBUG)

optimize: $(MAIN_OUTPUT_OPTIMIZE) $(OPERATORS_OUTPUT_OPTIMIZE)

# Debug target for main.cpp
$(MAIN_OUTPUT_DEBUG): $(MAIN_SOURCES) $(HEADERS)
	@if not exist $(OUTPUT_DIR_DEBUG) mkdir $(OUTPUT_DIR_DEBUG)
	$(CXX) $(CXXFLAGS_DEBUG) $(MAIN_SOURCES) -o $@

# Optimized target for main.cpp
$(MAIN_OUTPUT_OPTIMIZE): $(MAIN_SOURCES) $(HEADERS)
	@if not exist $(OUTPUT_DIR_OPTIMIZE) mkdir $(OUTPUT_DIR_OPTIMIZE)
	$(CXX) $(CXXFLAGS_OPTIMIZE) $(MAIN_SOURCES) -o $@

# Debug target for operators.cpp
$(OPERATORS_OUTPUT_DEBUG): $(OPERATORS_SOURCES) $(HEADERS)
	@if not exist $(OUTPUT_DIR_DEBUG) mkdir $(OUTPUT_DIR_DEBUG)
	$(CXX) $(CXXFLAGS_DEBUG) $(OPERATORS_SOURCES) -o $@

# Optimized target for operators.cpp
$(OPERATORS_OUTPUT_OPTIMIZE): $(OPERATORS_SOURCES) $(HEADERS)
	@if not exist $(OUTPUT_DIR_OPTIMIZE) mkdir $(OUTPUT_DIR_OPTIMIZE)
	$(CXX) $(CXXFLAGS_OPTIMIZE) $(OPERATORS_SOURCES) -o $@

clean:
	rm -rf $(OUTPUT_DIR_DEBUG) $(OUTPUT_DIR_OPTIMIZE)

.PHONY: clean
